// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.5
// source: partime.proto

package stub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHotPartTimeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartTime int64 `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   int64 `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
}

func (x *GetHotPartTimeReq) Reset() {
	*x = GetHotPartTimeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partime_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHotPartTimeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotPartTimeReq) ProtoMessage() {}

func (x *GetHotPartTimeReq) ProtoReflect() protoreflect.Message {
	mi := &file_partime_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotPartTimeReq.ProtoReflect.Descriptor instead.
func (*GetHotPartTimeReq) Descriptor() ([]byte, []int) {
	return file_partime_proto_rawDescGZIP(), []int{0}
}

func (x *GetHotPartTimeReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetHotPartTimeReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetHotPartTimeReq) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type GetPartTimeRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	List []*PartTime `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetPartTimeRsp) Reset() {
	*x = GetPartTimeRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partime_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPartTimeRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartTimeRsp) ProtoMessage() {}

func (x *GetPartTimeRsp) ProtoReflect() protoreflect.Message {
	mi := &file_partime_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartTimeRsp.ProtoReflect.Descriptor instead.
func (*GetPartTimeRsp) Descriptor() ([]byte, []int) {
	return file_partime_proto_rawDescGZIP(), []int{1}
}

func (x *GetPartTimeRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetPartTimeRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetPartTimeRsp) GetList() []*PartTime {
	if x != nil {
		return x.List
	}
	return nil
}

type GetPartTimeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    int32  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Openid string `protobuf:"bytes,2,opt,name=openid,proto3" json:"openid,omitempty"`
	Page   int32  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *GetPartTimeReq) Reset() {
	*x = GetPartTimeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partime_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPartTimeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartTimeReq) ProtoMessage() {}

func (x *GetPartTimeReq) ProtoReflect() protoreflect.Message {
	mi := &file_partime_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartTimeReq.ProtoReflect.Descriptor instead.
func (*GetPartTimeReq) Descriptor() ([]byte, []int) {
	return file_partime_proto_rawDescGZIP(), []int{2}
}

func (x *GetPartTimeReq) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetPartTimeReq) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *GetPartTimeReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type PartTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid        string  `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Status     int32   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Title      string  `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content    string  `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Tag        string  `protobuf:"bytes,6,opt,name=tag,proto3" json:"tag,omitempty"`
	Price      float32 `protobuf:"fixed32,7,opt,name=price,proto3" json:"price,omitempty"`
	Unit       string  `protobuf:"bytes,8,opt,name=unit,proto3" json:"unit,omitempty"`
	Province   string  `protobuf:"bytes,9,opt,name=province,proto3" json:"province,omitempty"`
	City       string  `protobuf:"bytes,10,opt,name=city,proto3" json:"city,omitempty"`
	Area       string  `protobuf:"bytes,11,opt,name=area,proto3" json:"area,omitempty"`
	Address    string  `protobuf:"bytes,12,opt,name=address,proto3" json:"address,omitempty"`
	Look       string  `protobuf:"bytes,13,opt,name=look,proto3" json:"look,omitempty"`
	CreatedAt  string  `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt  string  `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Deletetime string  `protobuf:"bytes,16,opt,name=deletetime,proto3" json:"deletetime,omitempty"`
}

func (x *PartTime) Reset() {
	*x = PartTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partime_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartTime) ProtoMessage() {}

func (x *PartTime) ProtoReflect() protoreflect.Message {
	mi := &file_partime_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartTime.ProtoReflect.Descriptor instead.
func (*PartTime) Descriptor() ([]byte, []int) {
	return file_partime_proto_rawDescGZIP(), []int{3}
}

func (x *PartTime) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PartTime) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PartTime) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PartTime) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PartTime) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PartTime) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *PartTime) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PartTime) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *PartTime) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *PartTime) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *PartTime) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *PartTime) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PartTime) GetLook() string {
	if x != nil {
		return x.Look
	}
	return ""
}

func (x *PartTime) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PartTime) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *PartTime) GetDeletetime() string {
	if x != nil {
		return x.Deletetime
	}
	return ""
}

var File_partime_proto protoreflect.FileDescriptor

var file_partime_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x61, 0x72, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x73, 0x74, 0x75, 0x62, 0x22, 0x66, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x74, 0x50,
	0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x5a, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x73, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x22, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x74, 0x75, 0x62, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x4e, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x50, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f,
	0x70, 0x65, 0x6e, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x80, 0x03, 0x0a, 0x08, 0x50, 0x61,
	0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74,
	0x61, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x61, 0x72, 0x65, 0x61, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x65, 0x61,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f,
	0x6f, 0x6b, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f, 0x6f, 0x6b, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0f, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x42, 0x08, 0x5a, 0x06,
	0x2e, 0x2f, 0x73, 0x74, 0x75, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_partime_proto_rawDescOnce sync.Once
	file_partime_proto_rawDescData = file_partime_proto_rawDesc
)

func file_partime_proto_rawDescGZIP() []byte {
	file_partime_proto_rawDescOnce.Do(func() {
		file_partime_proto_rawDescData = protoimpl.X.CompressGZIP(file_partime_proto_rawDescData)
	})
	return file_partime_proto_rawDescData
}

var file_partime_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_partime_proto_goTypes = []interface{}{
	(*GetHotPartTimeReq)(nil), // 0: stub.GetHotPartTimeReq
	(*GetPartTimeRsp)(nil),    // 1: stub.GetPartTimeRsp
	(*GetPartTimeReq)(nil),    // 2: stub.GetPartTimeReq
	(*PartTime)(nil),          // 3: stub.PartTime
}
var file_partime_proto_depIdxs = []int32{
	3, // 0: stub.GetPartTimeRsp.list:type_name -> stub.PartTime
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_partime_proto_init() }
func file_partime_proto_init() {
	if File_partime_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_partime_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHotPartTimeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partime_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPartTimeRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partime_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPartTimeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partime_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_partime_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_partime_proto_goTypes,
		DependencyIndexes: file_partime_proto_depIdxs,
		MessageInfos:      file_partime_proto_msgTypes,
	}.Build()
	File_partime_proto = out.File
	file_partime_proto_rawDesc = nil
	file_partime_proto_goTypes = nil
	file_partime_proto_depIdxs = nil
}
