// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: service.proto

package stub

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	GetHotPartTime(ctx context.Context, in *GetHotPartTimeReq, opts ...grpc.CallOption) (*GetPartTimeRsp, error)
	GetPartTime(ctx context.Context, in *GetPartTimeReq, opts ...grpc.CallOption) (*GetPartTimeRsp, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetHotPartTime(ctx context.Context, in *GetHotPartTimeReq, opts ...grpc.CallOption) (*GetPartTimeRsp, error) {
	out := new(GetPartTimeRsp)
	err := c.cc.Invoke(ctx, "/stub.UserService/GetHotPartTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetPartTime(ctx context.Context, in *GetPartTimeReq, opts ...grpc.CallOption) (*GetPartTimeRsp, error) {
	out := new(GetPartTimeRsp)
	err := c.cc.Invoke(ctx, "/stub.UserService/GetPartTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	GetHotPartTime(context.Context, *GetHotPartTimeReq) (*GetPartTimeRsp, error)
	GetPartTime(context.Context, *GetPartTimeReq) (*GetPartTimeRsp, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) GetHotPartTime(context.Context, *GetHotPartTimeReq) (*GetPartTimeRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHotPartTime not implemented")
}
func (UnimplementedUserServiceServer) GetPartTime(context.Context, *GetPartTimeReq) (*GetPartTimeRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPartTime not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetHotPartTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHotPartTimeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetHotPartTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stub.UserService/GetHotPartTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetHotPartTime(ctx, req.(*GetHotPartTimeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetPartTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPartTimeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetPartTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stub.UserService/GetPartTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetPartTime(ctx, req.(*GetPartTimeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stub.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHotPartTime",
			Handler:    _UserService_GetHotPartTime_Handler,
		},
		{
			MethodName: "GetPartTime",
			Handler:    _UserService_GetPartTime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
